DATASETS:
        TRAIN: ("cityscapes_fine_instance_seg_car_train","kitti_car_train_1")
        TEST: ('kitti_car_val_1',)
DATALOADER:
        NUM_WORKERS: 16
INPUT:
        MIN_SIZE_TRAIN: (800,)
SOLVER:
        BASE_LR: 0.0001
        MAX_ITER: 30000
        STEPS: []       
        WARMUP_ITERS: 0
        IMS_PER_BATCH: 2
MODEL:
        WEIGHTS: "path-to-trained-aggregator"
        META_ARCHITECTURE: 'STNPerspectiveRCNN'
        # RPN:
        #         HEAD_NAME: 'InvSTNHead'
        PROPOSAL_GENERATOR:
                NAME: 'SBRPN'
        STN_ARCH: 'FIVE_RANDOM_PERSPECTIVE'
        ROI_HEADS:
                # BATCH_SIZE_PER_IMAGE: 128   # faster, and good enough for this toy dataset (default: 512)
                NUM_CLASSES: 1
OUTPUT_DIR: "all_outs/city_fixed_stn_aggregate_fivestnperspective_student_teacher"
VIS_PERIOD: 500
