DATASETS:
        TRAIN: ("cityscapes_fine_instance_seg_person_train","MOT20_train")
        TEST: ('MOT20_val',)
DATALOADER:
        NUM_WORKERS: 16
INPUT:
        MIN_SIZE_TRAIN: (800,)
SOLVER:
        BASE_LR: 0.0001
        MAX_ITER: 30000
        STEPS: []       
        WARMUP_ITERS: 0
        IMS_PER_BATCH: 2
MODEL:
        WEIGHTS: "path-to-trained-aggregator"
        META_ARCHITECTURE: 'STNPerspectiveRCNN'

        PROPOSAL_GENERATOR:
                NAME: 'SBRPN'
        STN_ARCH: 'FIVE_RANDOM_PERSPECTIVE'
        ROI_HEADS:
                # BATCH_SIZE_PER_IMAGE: 128   # faster, and good enough for this toy dataset (default: 512)
                NUM_CLASSES: 1
OUTPUT_DIR: "all_outs/city_mot_person_fixed_stn_aggregate_fivestnperspective_student_teacher"
VIS_PERIOD: 500
