DATASETS:
        TRAIN: ("cityscapes_fine_instance_seg_person_train",)
        TEST: ('cityscapes_fine_instance_seg_person_val',)
DATALOADER:
        NUM_WORKERS: 16
INPUT:
        MIN_SIZE_TRAIN: (800,)
        
        CROP:
                ENABLED: True
                TYPE: "relative_range"
                SIZE: [0.3, 0.3]
SOLVER:
        BASE_LR: 0.01
        STEPS: (18000,)
        MAX_ITER: 24000
        IMS_PER_BATCH: 8
        
MODEL:
        WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
        ROI_HEADS:
                # BATCH_SIZE_PER_IMAGE: 128   # faster, and good enough for this toy dataset (default: 512)
                NUM_CLASSES: 1
OUTPUT_DIR: "all_outs/city_person_random_crop"
VIS_PERIOD: 500
